CREATE TABLE IF NOT EXISTS DISEASE (
  DISEASE_ID INT NOT NULL AUTO_INCREMENT,
  DISEASE_NAME VARCHAR (50) NOT NULL,
  CAUSE VARCHAR (150),
  COMMON_NAME (50),
  PRIMARY KEY(DISEASE_ID)
);

CREATE TABLE IF NOT EXISTS TIP (
  TIP_ID INT NOT NULL AUTO_INCREMENT,
  TIP_DES VARCHAR (300) NOT NULL,
  Task Name VARCHAR (150),
  PURPOSE VARCHAR (300),
  TYPE VARCHAR (50),
  WHEN VARCHAR (50),
  PRIMARY KEY (TIP_ID)
);

CREATE TABLE IF NOT EXISTS AREA (
  AREA_ID INT NOT NULL AUTO_INCREMENT,
  AREA_DESC VARCHAR (50),
  PRIMARY KEY (AREA_ID)
);

CREATE TABLE IF NOT EXISTS SYMPTOM (
  SYM_ID INT NOT NULL AUTO_INCREMENT,
  AREA_ID INT,
  SYM_DES VARCHAR(150) NOT NULL,
  PRIMARY KEY (SYM_ID),
  FOREIGN KEY (AREA_ID)
    REFERENCES AREA (AREA_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TASK (
  TASK_ID INT NOT NULL AUTO_INCREMENT,
  TASK_DES VARCHAR (150) NOT NULL,
  FREQUENCY INT NOT NULL,
  PURPOSE VARCHAR (150),
  PRIMARY KEY (TASK_ID)
);

CREATE TABLE IF NOT EXISTS SEASON (
  SEASON_ID INT NOT NULL,
  SEASON_NAME VARCHAR (50),
  PRIMARY KEY (SEASON_ID)
);

CREATE TABLE IF NOT EXISTS DISEASE_SYMPTOM (
  SYM_ID INT NOT NULL,
  DISEASE_ID INT NOT NULL,
  PRIMARY KEY(SYM_ID, DISEASE_ID),
  FOREIGN KEY (DISEASE_ID)
    REFERENCES DISEASE(DISEASE_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (SYM_ID)
    REFERENCES SYMPTOM (SYM_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SEASON_ENT_DATA (
  SEASON_ID INT NOT NULL,
  ADMID_NUM INT NOT NULL,
  PRIMARY KEY(SEASON_ID),
  FOREIGN KEY (SEASON_ID)
    REFERENCES SEASON(SEASON_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DISEASE_TASK (
  DISEASE_ID INT,
  TASK_ID INT,
  PRIMARY KEY (DISEASE_ID, TASK_ID),
  FOREIGN KEY (DISEASE_ID)
    REFERENCES DISEASE(DISEASE_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (TASK_ID)
    REFERENCES TASK (TASK_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DISEASE_TIP (
  DISEASE_ID INT,
  TIP_ID INT,
  SEASON_ID INT,
  PRIMARY KEY(DISEASE_ID, TIP_ID, SEASON_ID),
  FOREIGN KEY (DISEASE_ID)
    REFERENCES DISEASE(DISEASE_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (TIP_ID)
    REFERENCES TIP (TIP_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (SEASON_ID)
    REFERENCES SEASON(SEASON_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS DISEASE_SEASON (
  DISEASE_ID INT,
  SEASON_ID INT,
  PRIMARY KEY (DISEASE_ID, SEASON_ID),
  FOREIGN KEY (DISEASE_ID)
    REFERENCES DISEASE(DISEASE_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (SEASON_ID)
    REFERENCES TASK (SEASON_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LOCALITY (
  LOCALITY_ID INT NOT NULL AUTO_INCREMENT,
  SUBURB VARCHAR (50) NOT NULL,
  LGA VARCHAR (50) NOT NULL,
  POST_CODE INT,
  PRIMARY KEY(LOCALITY_ID)
);

CREATE TABLE IF NOT EXISTS LGA (
  LGA_ID INT NOT NULL AUTO_INCREMENT,
  LGA VARCHAR (50) NOT NULL,
  PARK_NAME VARCHAR (150),
  CATEGORY VARCHAR (150),
  ADDRESS VARCHAR (200),
  PRIMARY KEY(LGA_ID),
    FOREIGN KEY (LGA)
    REFERENCES LOCALITY(LGA)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
